name = "Butterfly Hunter"
description = "Attack butterflies with the attack button."
author = "InfinitePerplexity"
version = "0.1"
forumthread = ""
icon_atlas = "handy_icon.xml"
icon = "handy_icon.tex"
--dst_compatible = true
dont_starve_compatible = true
reign_of_giants_compatible = true
client_only_mod = true
api_version = 6
--dst_api_version = 10
--dst_compatible = true
dst_compatible = false
--all_clients_require_mod = false
shipwrecked_compatible = true